### ISSUE TITLE
Cannot launch when this mod is installed

### ISSUE THREAD

**Issue by mathuin** [malahx/QuickIVA#2]
To reproduce:
- Install the mod on a 1.1.2 instance of KSP
- Build a rocket with a probe core and an engine and maybe some fins
- Try to launch the rocket at the launch pad

What I expected:
- I expected the staging light to flash
- I expected the space bar to launch the rocket

What happened:
- The staging light stayed purple
- Pressing the space bar did not launch the rocket

About my setup:
- KSP 1.1.2
- Ubuntu 14.04.4 LTS
- GeForce GTX 560 Ti running NVIDIA 364.19

Installed mods:
- AutomatedScienceSampler 1.1.3
- BetterBurnTime 1.4.3
- BetterCrewAssignment 1.2.1
- CommunityResourcePack 0.5.2.0
- ConnectedLivingSpace 1.2.1.3
- ContractConfigurator 1.12.1
- ContractConfigurator-AnomalySurveyor 1.4.3
- ContractConfigurator-ContractPack-SCANsat v0.6.0.1
- ContractConfigurator-FieldResearch 1.1.7
- ContractConfigurator-KerbinSpaceStation 1:3.2.1.2
- ContractConfigurator-Tourism 1.4.2
- CrowdSourcedScience v3.0.2
- CustomBarnKit 1.1.8.0
- DockingPortAlignmentIndicator 6.4
- Dynamic Controls autodetected dll
- EngineLighting 1.4.5
- IndicatorLights 0.9.1
- KerbalAlarmClock v3.6.3.0
- KerbalEngineerRedux 1.1.1.0
- Kerbalism 1.0.0
- Kerbalism-Profile-Default 1.0.0
- KerbalJointReinforcement v3.1.7
- KerboKatzUtilities 1.3.7
- Kopernicus 2:release-1-0-5
- kRPC v0.3.4
- ksp_plugin_adapter autodetected dll
- KSP-AVC 1.1.6.1
- KSPSteamCtrlr autodetected dll
- LandingHeight 1.5
- MechJeb2 2.5.7.0
- ModuleManager 2.6.25
- OrbitalSurveyPlus 2.1.1
- PilotAssistant autodetected dll
- principia autodetected dll
- QuickIVA v1.12
- RasterPropMonitor 1:v0.26.0
- RasterPropMonitor-Core 1:v0.26.0
- RealPlume 2:v10.5.1
- RealPlume-StockConfigs v0.10.7
- SaveUpgradePipeline autodetected dll
- SCANsat v16.1
- Scatterer 2:v0.0246
- Scatterer-sunflare 2:v0.0246
- SmokeScreen 2.6.15.0
- Steamworks autodetected dll
- StockVisualEnhancements 1:0.7.1
- TakeCommand 1.4.1
- TextureReplacer v2.4.13
- ThrottleControlledAvionics v3.1.0-KSP-1.1.2
- Trajectories v1.6.2
- UnmannedBeforeManned 1.0.8.3
- VenStockRevamp v1.9.3
- WaypointManager 2.5.2

If necessary, I'll create a clean KSP directory (no mods other than what comes with KSP itself), then test just this mod and report back, but that's a pain, so I'll only do it if you ask. :-)

Let me know what else I can do to help!

**Comment by malahx** [comment]
Corrected with the last update ;)
